# Generated by Django 5.0.4 on 2024-04-12 20:14

import apps.main.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/files'), upload_to=apps.main.models.custom_upload_to),
        ),
    ]
