# Generated by Django 5.0.4 on 2024-04-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_filemetadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileMetadata',
        ),
    ]
