# Generated by Django 5.0.4 on 2024-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_filemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
