# Generated by Django 5.0.4 on 2024-04-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='storage',
            field=models.CharField(choices=[('local', 'Local Storage'), ('google_cloud', 'Google Cloud Storage')], default='local', max_length=50),
        ),
    ]
