# Generated by Django 5.0.4 on 2024-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_fileupload_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='storage',
            field=models.CharField(choices=[('local', 'Local Storage'), ('dropbox', 'Dropbox Storage')], default='local', max_length=50),
        ),
    ]
