# Generated by Django 5.0.4 on 2024-04-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_fileupload_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='storage',
        ),
    ]
