# Generated by Django 5.0.4 on 2024-04-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_fileupload_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
